steps:
 # build the container
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '--network=cloudbuild','-t', 'gcr.io/easybeauty-334916/server', '.']
 # push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/easybeauty-334916/server']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/cloud-builders/gcloud'
   args: ['run', 'deploy', 'easybeauty', '--image', 'gcr.io/easybeauty-334916/server', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']
images:
- 'gcr.io/easybeauty-334916/server'
